15:08:57,624 root INFO Starting experiment...
15:08:57,624 root INFO Loading GEMLER data...
15:09:32,106 root INFO GEMLER was loaded.
15:09:32,106 root INFO Running GridSearch for GEMLER...
15:10:11,377 root INFO GEMLER GridSearch done for KMeans.
15:10:19,632 root INFO GEMLER GridSearch done for KMedoids.
15:12:39,122 root INFO GEMLER GridSearch done for AgglomerativeClustering.
15:22:58,787 root INFO GEMLER GridSearch done for Birch.
15:23:03,577 root INFO GEMLER GridSearch done for DBSCAN.
15:25:59,417 root INFO GEMLER GridSearch done for OPTICS.
15:31:39,525 root INFO GEMLER GridSearch done for SOM.
15:33:22,706 root INFO GEMLER GridSearch done for AffinityPropagation.
17:11:02,257 root INFO GEMLER GridSearch done for SpectralClustering.
17:11:02,257 root INFO GEMLER GridSearch results saved to csv.
17:11:02,257 root INFO Loading METABRIC data...
17:13:11,143 root INFO METABRIC was loaded.
17:13:11,143 root INFO Running GridSearch for METABRIC...
17:17:57,547 root INFO METABRIC GridSearch done for KMeans.
17:18:47,486 root INFO METABRIC GridSearch done for KMedoids.
17:37:58,838 root INFO METABRIC GridSearch done for AgglomerativeClustering.
17:38:29,231 concurrent.futures ERROR exception calling callback for <Future at 0x7f13fc5968e0 state=finished raised TerminatedWorkerError>
Traceback (most recent call last):
  File "/home/michal/miniconda3/envs/clustering-genomic/lib/python3.9/site-packages/joblib/externals/loky/_base.py", line 26, in _invoke_callbacks
    callback(self)
  File "/home/michal/miniconda3/envs/clustering-genomic/lib/python3.9/site-packages/joblib/parallel.py", line 385, in __call__
    self.parallel.dispatch_next()
  File "/home/michal/miniconda3/envs/clustering-genomic/lib/python3.9/site-packages/joblib/parallel.py", line 834, in dispatch_next
    if not self.dispatch_one_batch(self._original_iterator):
  File "/home/michal/miniconda3/envs/clustering-genomic/lib/python3.9/site-packages/joblib/parallel.py", line 901, in dispatch_one_batch
    self._dispatch(tasks)
  File "/home/michal/miniconda3/envs/clustering-genomic/lib/python3.9/site-packages/joblib/parallel.py", line 819, in _dispatch
    job = self._backend.apply_async(batch, callback=cb)
  File "/home/michal/miniconda3/envs/clustering-genomic/lib/python3.9/site-packages/joblib/_parallel_backends.py", line 556, in apply_async
    future = self._workers.submit(SafeFunction(func))
  File "/home/michal/miniconda3/envs/clustering-genomic/lib/python3.9/site-packages/joblib/externals/loky/reusable_executor.py", line 176, in submit
    return super().submit(fn, *args, **kwargs)
  File "/home/michal/miniconda3/envs/clustering-genomic/lib/python3.9/site-packages/joblib/externals/loky/process_executor.py", line 1129, in submit
    raise self._flags.broken
joblib.externals.loky.process_executor.TerminatedWorkerError: A worker process managed by the executor was unexpectedly terminated. This could be caused by a segmentation fault while calling the function or by an excessive memory usage causing the Operating System to kill the worker.

The exit codes of the workers are {SIGKILL(-9)}
17:38:36,741 root CRITICAL A worker process managed by the executor was unexpectedly terminated. This could be caused by a segmentation fault while calling the function or by an excessive memory usage causing the Operating System to kill the worker.

The exit codes of the workers are {SIGKILL(-9)}
Traceback (most recent call last):
  File "/home/michal/clustering-genomic-data/experiment/run_experiment.py", line 131, in main
    grid_search.fit(
  File "/home/michal/clustering-genomic-data/experiment/clustering_grid_search.py", line 475, in fit
    self._run_search(evaluate_candidates)
  File "/home/michal/miniconda3/envs/clustering-genomic/lib/python3.9/site-packages/sklearn/model_selection/_search.py", line 1388, in _run_search
    evaluate_candidates(ParameterGrid(self.param_grid))
  File "/home/michal/clustering-genomic-data/experiment/clustering_grid_search.py", line 422, in evaluate_candidates
    out = parallel(
  File "/home/michal/miniconda3/envs/clustering-genomic/lib/python3.9/site-packages/sklearn/utils/parallel.py", line 63, in __call__
    return super().__call__(iterable_with_config)
  File "/home/michal/miniconda3/envs/clustering-genomic/lib/python3.9/site-packages/joblib/parallel.py", line 1098, in __call__
    self.retrieve()
  File "/home/michal/miniconda3/envs/clustering-genomic/lib/python3.9/site-packages/joblib/parallel.py", line 975, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "/home/michal/miniconda3/envs/clustering-genomic/lib/python3.9/site-packages/joblib/_parallel_backends.py", line 567, in wrap_future_result
    return future.result(timeout=timeout)
  File "/home/michal/miniconda3/envs/clustering-genomic/lib/python3.9/concurrent/futures/_base.py", line 446, in result
    return self.__get_result()
  File "/home/michal/miniconda3/envs/clustering-genomic/lib/python3.9/concurrent/futures/_base.py", line 391, in __get_result
    raise self._exception
  File "/home/michal/miniconda3/envs/clustering-genomic/lib/python3.9/site-packages/joblib/externals/loky/_base.py", line 26, in _invoke_callbacks
    callback(self)
  File "/home/michal/miniconda3/envs/clustering-genomic/lib/python3.9/site-packages/joblib/parallel.py", line 385, in __call__
    self.parallel.dispatch_next()
  File "/home/michal/miniconda3/envs/clustering-genomic/lib/python3.9/site-packages/joblib/parallel.py", line 834, in dispatch_next
    if not self.dispatch_one_batch(self._original_iterator):
  File "/home/michal/miniconda3/envs/clustering-genomic/lib/python3.9/site-packages/joblib/parallel.py", line 901, in dispatch_one_batch
    self._dispatch(tasks)
  File "/home/michal/miniconda3/envs/clustering-genomic/lib/python3.9/site-packages/joblib/parallel.py", line 819, in _dispatch
    job = self._backend.apply_async(batch, callback=cb)
  File "/home/michal/miniconda3/envs/clustering-genomic/lib/python3.9/site-packages/joblib/_parallel_backends.py", line 556, in apply_async
    future = self._workers.submit(SafeFunction(func))
  File "/home/michal/miniconda3/envs/clustering-genomic/lib/python3.9/site-packages/joblib/externals/loky/reusable_executor.py", line 176, in submit
    return super().submit(fn, *args, **kwargs)
  File "/home/michal/miniconda3/envs/clustering-genomic/lib/python3.9/site-packages/joblib/externals/loky/process_executor.py", line 1129, in submit
    raise self._flags.broken
joblib.externals.loky.process_executor.TerminatedWorkerError: A worker process managed by the executor was unexpectedly terminated. This could be caused by a segmentation fault while calling the function or by an excessive memory usage causing the Operating System to kill the worker.

The exit codes of the workers are {SIGKILL(-9)}
17:38:36,747 root INFO METABRIC GridSearch failed for Birch. Skipping...
17:39:00,28 root INFO METABRIC GridSearch done for DBSCAN.
17:55:00,378 root INFO METABRIC GridSearch done for OPTICS.
18:41:32,780 root INFO METABRIC GridSearch done for SOM.
18:45:14,687 root INFO METABRIC GridSearch done for AffinityPropagation.
19:00:58,295 root INFO METABRIC GridSearch done for SpectralClustering.
19:00:58,296 root INFO METABRIC GridSearch results saved to csv.
